# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

validate_database_files <- function(db_prefix, num_genes) {
    .Call('_gesel_validate_database_files', PACKAGE = 'gesel', db_prefix, num_genes)
}

validate_gene_files <- function(gene_prefix, types) {
    .Call('_gesel_validate_gene_files', PACKAGE = 'gesel', gene_prefix, types)
}

