#' Rename genes in their sets
#'
#' Convert genes in sets from row indices to their identifiers.
#'
#' @param species String specifying the taxonomy ID of the species of interest.
#' @param sets List of integer vectors, typically generated by \code{\link{fetchGenesForAllSets}} or \code{\link{fetchGenesForSomeSets}}.
#' Each vector represents a gene set and contains gene indices, i.e., row indices into the data frame returned by \code{\link{fetchAllGenes}}.
#' @param type String specifying the type of gene identifier to convert to.
#' This is typically one of \code{"symbol"}, \code{"ensembl"} or \code{"entrez"}.
#' @param config Configuration list, typically created by \code{\link{newConfig}}.
#' If \code{NULL}, the default configuration is used.
#' 
#' @return A list of the same length as \code{sets}.
#' Each entry is now a character vector containing the specified identifiers for the genes in the corresponding set.
#'
#' @details
#' If a gene has no identifiers of the specified \code{type}, it is omitted from the affected character vectors in the output list.
#' If a gene has multiple identifiers of the specified \code{type}, all identifiers are reported in the affected character vectors in the output list.
#' As a result, the apparent size of the gene sets from the output list (e.g., with \code{\link{lengths}}) may not agree with the real sizes in \code{\link{fetchSetSizes}}.
#'
#' @author Aaron Lun
#' @examples
#' example.sets <- fetchGenesForSomeSets("9606", 1:50)
#' head(example.sets)
#' renamed.sets <- renameGenesInSets("9606", example.sets, "symbol")
#' head(renamed.sets)
#'
#' @export
renameGenesInSets <- function(species, sets, type, config = NULL) {
    all.genes <- fetchAllGenes(species, type, config = config)[,type]
    .renameGenesInSets(all.genes, sets)
}

.renameGenesInSets <- function(gene.ids, sets) {
    raw.genes <- gene.ids[unlist(sets)]
    set.idx <- rep(seq_along(sets), lengths(sets))
    set.idx <- rep(set.idx, lengths(raw.genes))

    # Strip out duplicates quickly.
    collected <- data.frame(X = as.character(unlist(raw.genes)), Y = set.idx)
    collected <- unique(collected)

    unname(
        split(
            collected$X,
            factor(collected$Y, seq_along(sets)),
            drop = FALSE
        )
    )
}
