#' Rename genes in their sets
#'
#' Convert genes in sets from row indices to their identifiers.
#'
#' @param species String specifying the taxonomy ID of the species of interest.
#' @param sets List of integer vectors, typically generated by \code{\link{fetchGenesForAllSets}} or \code{\link{fetchGenesForSomeSets}}.
#' Each vector represents a gene set and contains gene indices, i.e., row indices into the data frame returned by \code{\link{fetchAllGenes}}.
#' @param type String specifying the type of gene identifier to convert to.
#' This is typically one of \code{"symbol"}, \code{"ensembl"} or \code{"entrez"}.
#' @param config Configuration list, typically created by \code{\link{newConfig}}.
#' If \code{NULL}, the default configuration is used.
#' 
#' @return A list of the same length as \code{sets}.
#' Each entry is now a character vector containing the specified identifiers for the genes in the corresponding set.
#'
#' @author Aaron Lun
#' @examples
#' example.sets <- fetchGenesForSomeSets("9606", 1:50)
#' str(example.sets)
#' renamed.sets <- renameGenesInSets("9606", example.sets, "symbol")
#' str(renamed.sets)
#'
#' @export
renameGenesInSets <- function(species, sets, type, config = NULL) {
    all.genes <- fetchAllGenes(species, type, config = config)[,type]
    raw.genes <- all.genes[unlist(sets)]
    set.idx <- rep(seq_along(sets), lengths(sets))
    set.idx <- rep(set.idx, lengths(raw.genes))
    unname(
        split(
            as.character(unlist(raw.genes)),
            factor(set.idx, seq_along(sets)),
            drop=FALSE
        )
    )
}
